### ISSUE TITLE
Raise RuntimeError("grad can be implicitly created only for scalar outputs")

### ISSUE THREAD

**Issue by SihangXie** [winycg/L-MCL#1]
Hi, congrats for the accept to TPAMI!

When I run `main_layer_mcl_cifar_meta.py` on 2 GPUs with DataParallel, the following error occur: 

> Traceback (most recent call last):
  File "/home/og/.pycharm_helpers/pydev/pydevd.py", line 1534, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/og/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/og/XieSH/models/LMCL/main_layer_mcl_cifar_meta.py", line 419, in <module>
    train(epoch, criterion_list, aggregator, meta_optimizer, weight_optimizer)
  File "/home/og/XieSH/models/LMCL/main_layer_mcl_cifar_meta.py", line 204, in train
    loss.backward()
  File "/home/og/miniconda3/envs/xsh36/lib/python3.6/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/og/miniconda3/envs/xsh36/lib/python3.6/site-packages/torch/autograd/__init__.py", line 126, in backward
    grad_tensors_ = _make_grads(tensors, grad_tensors_)
  File "/home/og/miniconda3/envs/xsh36/lib/python3.6/site-packages/torch/autograd/__init__.py", line 50, in _make_grads
    raise RuntimeError("grad can be implicitly created only for scalar outputs")
RuntimeError: grad can be implicitly created only for scalar outputs

I debug the code and found that [`criterion_mcl`](https://github.com/winycg/L-MCL/blob/2c0901efbee5ef35e90bcae751183a616bf806fa/main_layer_mcl_cifar_meta.py#L208C8-L208C103) return 2 elements like `[loss1, loss2]` . 

My question is : How should I fix this bug?

I would greatly appreciate it if I could receive your reply.

**Comment by winycg** [comment]
Hi, thanks for your attention of our work. Could you tell me your pytorch version? Our code could run OK over torch==1.7.1.

**Comment by SihangXie** [comment]
Hi, my PyTorch version is 1.7.1 too. Python version is 3.6

**Comment by winycg** [comment]
Hi, I find the problem. Over CIFAR, you need only one GPU to run this code, because I do not gather scalar outputs to one loss scalar when more than 1 GPUs.

**Comment by SihangXie** [comment]
Thanks for your answer, I understand. God bless you
